# Generated by Django 4.2.9 on 2026-03-23 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fiches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficheexterne',
            name='executed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'exécution"),
        ),
        migrations.AddField(
            model_name='ficheexterne',
            name='executed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions_externes', to=settings.AUTH_USER_MODEL, verbose_name='Exécuté par'),
        ),
        migrations.AddField(
            model_name='ficheexterne',
            name='execution_note',
            field=models.TextField(blank=True, default='', verbose_name="Note d'exécution"),
        ),
        migrations.AddField(
            model_name='ficheexterne',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de réception'),
        ),
        migrations.AddField(
            model_name='ficheinterne',
            name='executed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'exécution"),
        ),
        migrations.AddField(
            model_name='ficheinterne',
            name='executed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions_internes', to=settings.AUTH_USER_MODEL, verbose_name='Exécuté par'),
        ),
        migrations.AddField(
            model_name='ficheinterne',
            name='execution_note',
            field=models.TextField(blank=True, default='', verbose_name="Note d'exécution"),
        ),
        migrations.AddField(
            model_name='ficheinterne',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de réception'),
        ),
        migrations.AlterField(
            model_name='ficheexterne',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('PENDING_MANAGER', 'En attente du Supérieur Hiérarchique'), ('PENDING_DIRECTOR', 'En attente du DG'), ('APPROVED', 'Approuvée'), ('REJECTED', 'Rejetée'), ('IN_EXECUTION', "En cours d'exécution"), ('DELIVERED', 'Livrée / Réceptionnée')], default='DRAFT', max_length=30, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='ficheinterne',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('PENDING_MANAGER', 'En attente du Supérieur Hiérarchique'), ('PENDING_DAF', 'En attente du DAF'), ('PENDING_DIRECTOR', 'En attente du DG'), ('APPROVED', 'Approuvée'), ('REJECTED', 'Rejetée'), ('IN_EXECUTION', "En cours d'exécution"), ('DELIVERED', 'Livrée / Réceptionnée')], default='DRAFT', max_length=30, verbose_name='Statut'),
        ),
    ]
