# Generated by Django 4.2.9 on 2026-03-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0002_add_execution_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficheexterne',
            name='execution_fournisseur',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Fournisseur / Prestataire'),
        ),
        migrations.AddField(
            model_name='ficheexterne',
            name='execution_mode_paiement',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Mode de paiement'),
        ),
        migrations.AddField(
            model_name='ficheexterne',
            name='execution_montant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Montant décaissé'),
        ),
        migrations.AddField(
            model_name='ficheexterne',
            name='execution_numero_facture',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='N° Facture'),
        ),
        migrations.AddField(
            model_name='ficheexterne',
            name='execution_reference',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Référence bon de commande'),
        ),
        migrations.AddField(
            model_name='ficheinterne',
            name='execution_fournisseur',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Fournisseur / Prestataire'),
        ),
        migrations.AddField(
            model_name='ficheinterne',
            name='execution_mode_paiement',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Mode de paiement'),
        ),
        migrations.AddField(
            model_name='ficheinterne',
            name='execution_montant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Montant décaissé'),
        ),
        migrations.AddField(
            model_name='ficheinterne',
            name='execution_numero_facture',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='N° Facture'),
        ),
        migrations.AddField(
            model_name='ficheinterne',
            name='execution_reference',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Référence bon de commande'),
        ),
        migrations.AlterField(
            model_name='ficheexterne',
            name='execution_note',
            field=models.TextField(blank=True, default='', verbose_name='Observations'),
        ),
        migrations.AlterField(
            model_name='ficheinterne',
            name='execution_note',
            field=models.TextField(blank=True, default='', verbose_name='Observations'),
        ),
    ]
