# Generated by Django 4.2.9 on 2026-03-23 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fiches', '0003_add_execution_detail_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficheexterne',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('PENDING_MANAGER', 'En attente du Supérieur Hiérarchique'), ('PENDING_DIRECTOR', 'En attente du DG'), ('PENDING_CLARIFICATION_DIR', 'Clarification demandée (DG)'), ('APPROVED', 'Approuvée'), ('REJECTED', 'Rejetée'), ('IN_EXECUTION', "En cours d'exécution"), ('DELIVERED', 'Livrée / Réceptionnée')], default='DRAFT', max_length=30, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='ficheinterne',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('PENDING_MANAGER', 'En attente du Supérieur Hiérarchique'), ('PENDING_DAF', 'En attente du DAF'), ('PENDING_DIRECTOR', 'En attente du DG'), ('PENDING_CLARIFICATION_DAF', 'Clarification demandée (DAF)'), ('PENDING_CLARIFICATION_DIR', 'Clarification demandée (DG)'), ('APPROVED', 'Approuvée'), ('REJECTED', 'Rejetée'), ('IN_EXECUTION', "En cours d'exécution"), ('DELIVERED', 'Livrée / Réceptionnée')], default='DRAFT', max_length=30, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='validation',
            name='status',
            field=models.CharField(choices=[('FAVORABLE', 'Favorable'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté'), ('CLARIFICATION_REQUESTED', 'Clarification demandée'), ('CLARIFICATION_RESPONDED', 'Clarification fournie')], max_length=30, verbose_name='Décision'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('notification_type', models.CharField(choices=[('FAVORABLE', 'Avis favorable'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté'), ('CLARIFICATION_REQUEST', 'Demande de clarification'), ('CLARIFICATION_RESPONSE', 'Clarification fournie')], max_length=30, verbose_name='Type')),
                ('fiche_type', models.CharField(blank=True, choices=[('INTERNE', 'Interne'), ('EXTERNE', 'Externe')], default='', max_length=10, verbose_name='Type de fiche')),
                ('fiche_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID Fiche')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Expéditeur')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
