# Generated by Django 4.2.9 on 2026-03-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0004_add_clarification_statuses_and_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('SUBMITTED', 'Besoin soumis'), ('FAVORABLE', 'Avis favorable'), ('APPROVED', 'Accord pour exécution'), ('REJECTED', 'Rejeté'), ('CLARIFICATION_REQUEST', 'Demande de clarification'), ('CLARIFICATION_RESPONSE', 'Clarification fournie'), ('IN_EXECUTION', "En cours d'exécution"), ('DELIVERED', 'Livré / Réceptionné'), ('BON_EMIS', 'Bon de paiement émis'), ('BON_VALIDE', 'Bon de paiement validé'), ('BON_ANNULE', 'Bon de paiement annulé')], max_length=30, verbose_name='Type'),
        ),
    ]
