# Generated by Django 4.2.9 on 2026-04-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0006_add_reference_to_fiches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficheexterne',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('PENDING_MANAGER', 'En attente du Supérieur Hiérarchique'), ('PENDING_DAF', 'En attente du DAF'), ('PENDING_DIRECTOR', 'En attente du DG'), ('PENDING_CLARIFICATION_DAF', 'Clarification demandée (DAF)'), ('PENDING_CLARIFICATION_DIR', 'Clarification demandée (DG)'), ('APPROVED', 'Approuvée'), ('REJECTED', 'Rejetée'), ('IN_EXECUTION', "En cours d'exécution"), ('DELIVERED', 'Livrée / Réceptionnée')], default='DRAFT', max_length=30, verbose_name='Statut'),
        ),
    ]
