# Generated by Django 4.2.9 on 2026-03-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bons_paiement', '0002_bon_paiement_fiche_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonpaiement',
            name='mode_paiement',
            field=models.CharField(choices=[('ESPECE', 'Espèce'), ('CHEQUE', 'Chèque')], max_length=20, verbose_name='Mode de paiement'),
        ),
    ]
